Expose zlib constants for backwards compat #747
nmoinvaz/minizip pull request #750
Opened 2023-12-16 03:34 UTC by brad0

Building a project that had an internal copy of minizip 1.x, but
preferring an external library, with minizip 4.x showed that the
compat layer was not exposing some constants from zlib that
minizip 1.x headers did.

2023-12-17 17:36 UTC, nmoinvaz commented on mz_compat_shim.h.in
> +#include "zlib.h"
```suggestion
#include <zlib.h>
```

2023-12-17 17:37 UTC, nmoinvaz commented on mz_compat.h
> -#ifndef Z_DEFLATED
I think this needs to be added back as internal minizip library depends on it.

2023-12-18 17:05 UTC, nmoinvaz commented on mz_compat.h
> -#ifndef Z_DEFLATED
This still needs to be added back.

2023-12-18 17:05 UTC, nmoinvaz commented on mz_compat.h
> -#ifndef Z_DEFLATED
Hmm maybe not.

2023-12-18 17:08 UTC, nmoinvaz commented
D:\a\minizip-ng\minizip-ng\mz_compat.h(19,10): fatal  error C1083: Cannot open include file: 'zlib.h': No such file or directory [D:\a\minizip-ng\minizip-ng\test\gtest_minizip.vcxproj]

2023-12-18 18:16 UTC, nmoinvaz commented
I could be wrong, but I think this CMake: 
https://github.com/zlib-ng/minizip-ng/blob/ef3ef9a4b8319b94d174d8911404a8b98d319ac7/test/CMakeLists.txt#L63-L65

needs to add `${ZLIB_SOURCE_DIR}` and `${ZLIB_BINARY_DIR}`.

2023-12-22 03:17 UTC, nmoinvaz commented
Should I wait on this PR to make a new release?

2023-12-22 04:55 UTC, brad0 commented
> Should I wait on this PR to make a new release?

Go for 4.0.4.

2024-10-28 22:09 UTC, Neustradamus commented
For information, minizip-ng 4.0.7 has been released (2024-06-15).

2024-11-01 16:27 UTC, Coeur requested changes

2024-11-01 16:27 UTC, Coeur commented on CMakeLists.txt
> +        ${ZLIB_BINARY_DIR})
From my experiments, that part isn't needed. It's actually causing extra build issues (for Windows).

I came up with a solution that builds in #815

2024-11-11 21:20 UTC, closed without merging